# -*- coding: utf-8 -*-
"""train_xlm_roberta.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DEQ1Fwe4mJIVGi8GmXSwRrlqkBZJSuto
"""

!pip install transformers
!pip install datasets
!pip install accelerate
!pip install scikit-learn

from google.colab import files

uploaded = files.upload()

import pandas as pd

df = pd.read_csv(
    "merlin_scoring_dataset_v2.csv"
)

print(df.shape)

df.head()

from sklearn.model_selection import train_test_split

train_df, test_df = train_test_split(
    df,
    test_size=0.2,
    random_state=42
)

print(len(train_df))
print(len(test_df))

"""Convert To HF Dataset"""

from datasets import Dataset

train_dataset = Dataset.from_pandas(
    train_df[["model_input", "score"]]
)

test_dataset = Dataset.from_pandas(
    test_df[["model_input", "score"]]
)

"""Rename Scores to Labels"""

train_dataset = train_dataset.rename_column(
    "score",
    "labels"
)

test_dataset = test_dataset.rename_column(
    "score",
    "labels"
)

"""Load Tokenizer"""

from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained(
    "xlm-roberta-base"
)

"""Tokenize"""

def tokenize_function(examples):

    return tokenizer(
        examples["model_input"],
        truncation=True,
        padding="max_length",
        max_length=512
    )

tokenized_train = train_dataset.map(
    tokenize_function,
    batched=True
)

tokenized_test = test_dataset.map(
    tokenize_function,
    batched=True
)

"""Prepare For Trainer"""

from transformers import DataCollatorWithPadding

data_collator = DataCollatorWithPadding(
    tokenizer=tokenizer
)

"""Load Model"""

from transformers import AutoModelForSequenceClassification

model = AutoModelForSequenceClassification.from_pretrained(
    "xlm-roberta-base",
    num_labels=1
)

"""Metrics"""

import numpy as np

from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

def compute_metrics(eval_pred):

    predictions, labels = eval_pred

    predictions = predictions.squeeze()

    mae = mean_absolute_error(
        labels,
        predictions
    )

    rmse = np.sqrt(
        mean_squared_error(
            labels,
            predictions
        )
    )

    r2 = r2_score(
        labels,
        predictions
    )

    return {
        "mae": mae,
        "rmse": rmse,
        "r2": r2
    }

"""Training Arguments"""

from transformers import TrainingArguments

training_args = TrainingArguments(
    output_dir="./results",

    num_train_epochs=3,

    per_device_train_batch_size=8,

    per_device_eval_batch_size=8,

    eval_strategy="epoch",

    save_strategy="epoch",

    learning_rate=2e-5,

    weight_decay=0.01
)

"""Trainer"""

from transformers import Trainer

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_train,
    eval_dataset=tokenized_test,
    compute_metrics=compute_metrics,
    data_collator=data_collator
)

print("Trainer created.")

"""Start Training"""

trainer.train()

trainer.save_model("xlm_roberta_scoring_model")

tokenizer.save_pretrained(
    "xlm_roberta_scoring_model"
)